# Generated by Django 3.2.7 on 2022-01-28 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('order_code', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('received', 'Received'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='created', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
